# Tests sourcing this include file will run at the end one at a time
# on a same worker process.


auth_sec.system_user_kill_connection
sys_vars.innodb_monitor_reset_basic
perfschema.idx_compare_mutex_instances
perfschema.idx_threads
innodb.iodku_debug
innodb.log_encrypt_4
innodb.innodb_idle_flush_pct
innodb_gis.rtree_split_geographic
innodb.ddl_crash_alter_partition
innodb.ddl_crash_alter_table_partition
main.sum_distinct-big
main.blackhole_plugin
xcluster.bug11006344
xcluster.dumpbinlog
xcluster.learner_after_purgelog
xcluster.show_cluster_health
xcluster.recovery_apply_binlog
xcluster.purge_log
