# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lm.requestInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lm.requestInfo.proto',
  package='lm',
  serialized_pb='\n\x14lm.requestInfo.proto\x12\x02lm\"\xa0\x02\n\x12requestInfoWrapper\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0f\n\x07linkPin\x18\x02 \x01(\t\x12\x0e\n\x06\x61ppKey\x18\x03 \x01(\t\x12\x11\n\tmessageID\x18\x04 \x01(\t\x12\x0b\n\x03\x63md\x18\x05 \x01(\t\x12\x13\n\x0b\x63lusterName\x18\x06 \x01(\t\x12\x11\n\tcustInsID\x18\x07 \x01(\t\x12\x13\n\x0b\x63ustInsName\x18\x08 \x01(\t\x12\x10\n\x08masterIP\x18\t \x01(\t\x12\x12\n\nmasterPort\x18\n \x01(\t\x12\x0f\n\x07slaveIP\x18\x0b \x01(\t\x12\x11\n\tslavePort\x18\x0c \x01(\t\x12\x0e\n\x06\x64\x62Type\x18\r \x01(\t\x12\x10\n\x08\x64iskSize\x18\x0e \x01(\t\x12\x0f\n\x07sqlList\x18\x0f \x03(\tBE\n-com.ali.alirockscluster.client.socket.messageB\x14RequestInfoWrapperDO')




_REQUESTINFOWRAPPER = _descriptor.Descriptor(
  name='requestInfoWrapper',
  full_name='lm.requestInfoWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='lm.requestInfoWrapper.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='linkPin', full_name='lm.requestInfoWrapper.linkPin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='appKey', full_name='lm.requestInfoWrapper.appKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='messageID', full_name='lm.requestInfoWrapper.messageID', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cmd', full_name='lm.requestInfoWrapper.cmd', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='clusterName', full_name='lm.requestInfoWrapper.clusterName', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custInsID', full_name='lm.requestInfoWrapper.custInsID', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custInsName', full_name='lm.requestInfoWrapper.custInsName', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='masterIP', full_name='lm.requestInfoWrapper.masterIP', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='masterPort', full_name='lm.requestInfoWrapper.masterPort', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slaveIP', full_name='lm.requestInfoWrapper.slaveIP', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slavePort', full_name='lm.requestInfoWrapper.slavePort', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dbType', full_name='lm.requestInfoWrapper.dbType', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='diskSize', full_name='lm.requestInfoWrapper.diskSize', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sqlList', full_name='lm.requestInfoWrapper.sqlList', index=14,
      number=15, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=317,
)

DESCRIPTOR.message_types_by_name['requestInfoWrapper'] = _REQUESTINFOWRAPPER

class requestInfoWrapper(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUESTINFOWRAPPER

  # @@protoc_insertion_point(class_scope:lm.requestInfoWrapper)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n-com.ali.alirockscluster.client.socket.messageB\024RequestInfoWrapperDO')
# @@protoc_insertion_point(module_scope)
