# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lm.responseInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lm.responseInfo.proto',
  package='lm',
  serialized_pb='\n\x15lm.responseInfo.proto\x12\x02lm\";\n\x13responseInfoWrapper\x12\x11\n\tmessageID\x18\x01 \x01(\t\x12\x11\n\terrorCode\x18\x02 \x01(\tB9\n com.ali.alirockscluster.pojo.messageB\x15ResponseInfoWrapperDO')




_RESPONSEINFOWRAPPER = _descriptor.Descriptor(
  name='responseInfoWrapper',
  full_name='lm.responseInfoWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageID', full_name='lm.responseInfoWrapper.messageID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='lm.responseInfoWrapper.errorCode', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=29,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['responseInfoWrapper'] = _RESPONSEINFOWRAPPER

class responseInfoWrapper(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _RESPONSEINFOWRAPPER

  # @@protoc_insertion_point(class_scope:lm.responseInfoWrapper)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), '\n com.ali.alirockscluster.pojo.messageB\025ResponseInfoWrapperDO')
# @@protoc_insertion_point(module_scope)
