# local transaction
db_type = "mysql"
row_count = 10000
initial_balance = 1000
verbose = true
enable_cts = false
enable_ssot = false
enable_uk = true

[check_balance]
enabled = true
threads = 1

[read_snapshot]
enabled = true
threads = 1

[read_too_old_snapshot]
enabled = true
threads = 0

[read_long]
enabled = true
threads = 0
interval = "5s"
total = "20m"

[check_secondary_index]
enabled = true
threads = 1

[transfer_simple]
enabled = true
threads = 10

[user_manage]
enabled = true
threads = 10