/*****************************************************************************

Copyright (c) 2013, 2023, Alibaba and/or its affiliates. All Rights Reserved.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License, version 2.0, as published by the
Free Software Foundation.

This program is also distributed with certain software (including but not
limited to OpenSSL) that is licensed under separate terms, as designated in a
particular file or component or in included license documentation. The authors
of MySQL hereby grant you an additional permission to link the program and
your derivative works with the separately licensed software that they have
included with MySQL.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License, version 2.0,
for more details.

You should have received a copy of the GNU General Public License along with
this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin St, Fifth Floor, Boston, MA 02110-1301  USA

*****************************************************************************/

/** @file sql/xa_specification.h

  Transaction coordinator log structure specification.

  Created 2023-06-14 by Jianwei.zhao
 *******************************************************/

#ifndef SQL_XA_SPECIFICATION_H
#define SQL_XA_SPECIFICATION_H

#include "sql/lizard/lizard_service.h"  // MyVisionGCN...
#include "sql/xa.h"
#include "sql/xa/lizard_cmmt_policy.h"

/**
 * Transaction coordinator should write log to complete XA,
 * except of xid for all TC_LOG category,  Other specifications are maybe
 * record according to different implemention.
 */

/**
 * transaction coordinator log specification, except of xid.
 */
class XA_specification {
 public:
  XA_specification() : m_cpolicy(nullptr), m_allocated(false) {}

  virtual ~XA_specification() {
    if (m_allocated) {
      delete m_cpolicy;
      m_allocated = false;
    }
    m_cpolicy = nullptr;
  }

  /** TODO: print all information. */
  virtual std::string print() { return "GCN"; }

  virtual void clear() {
    if (m_allocated) {
      delete m_cpolicy;
      m_allocated = false;
    }
    m_cpolicy = nullptr;
  }

  XA_specification &operator=(const XA_specification &other) = delete;

  /** If has gcn, then it must have one valid commit_policy. */
  bool has_gcn() const {
    return m_cpolicy != nullptr && m_cpolicy->has_decided();
  }

  void copy_xa_to_trx(trx_t *trx) {
    assert(m_cpolicy->has_decided());

    m_cpolicy->copy_to_trx(trx);
  }

  /**
   * Set XA_specification when recovering.
   *
   * @param[in] cpolicy : The commit policy generated by GCN Event in recovery.
   */
  void set_when_recovery(const lizard::Commit_policy *cpolicy) {
    /**
     * There has only two cases when recovering:
     * 1. Binlog_ac_prepare_policy
     * 2. Binlog_commit_policy
     */
    assert(cpolicy != nullptr && cpolicy->has_decided());
    assert(dynamic_cast<const lizard::Binlog_commit_policy *>(cpolicy) !=
               nullptr ||
           dynamic_cast<const lizard::Binlog_ac_prepare_policy *>(cpolicy) !=
               nullptr);
    assert(!m_allocated);

    m_cpolicy = cpolicy;
  }

  /**
   * Set XA_specification when committing.
   *
   * @param[in] cpolicy: The commit policy which comes from cpolicy_ctx.
   */
  void set_when_commit(const lizard::Commit_policy *cpolicy) {
    assert(m_cpolicy == nullptr);
    assert(cpolicy != nullptr && cpolicy->has_decided());
    assert(!m_allocated);

    m_cpolicy = cpolicy;
  }

  [[nodiscard]] virtual XA_specification *clone() const {
    return new XA_specification(*this);
  }

  [[nodiscard]] virtual XA_specification *clone(MEM_ROOT *mem_root) const {
    return new (mem_root) XA_specification(*this, mem_root);
  }

 protected:
  XA_specification(const XA_specification &other)
      : m_cpolicy(nullptr), m_allocated(false) {
    if (other.m_cpolicy != nullptr) {
      m_cpolicy = other.m_cpolicy->clone();
      m_allocated = true;
    }
  }
  XA_specification(const XA_specification &other, MEM_ROOT *mem_root)
      : m_cpolicy(nullptr), m_allocated(false) {
    if (other.m_cpolicy != nullptr) {
      m_cpolicy = other.m_cpolicy->clone(mem_root);
    }
  }

 private:
  /**
   * There are three cases for XA_specification:
   * 1. When processing GCN Log event in recovery(i.e. process_gcn_event), we
   * will call @function:set_when_recovery to set Binlog_xa_specifiaction.
   * In this case, we don't need to manage the commit policy, cause that it
   * was managed by mem_root.
   *
   * 2. After processing GCN Log event in recovery, XA_specification will be
   * collected to XA_spec_list. For this case, it will be allocated with
   * specified mem_root. We don't need to manage the commit policy.
   *
   * 3. When exectuting xa commit/rollback in detached mode, we will call
   * @function:set_when_commit to set XA_specification cause that we can not get
   * the commit_policy in innodb. Notice that this could also happen in
   * replaying the binlog in replica.
   * In this case, we don't need to manage the commit policy cause that
   * thd->cpolicy_ctx will do it.
   */

  const lizard::Commit_policy *m_cpolicy;

  /** Whether m_cpolicy is allocated by this object. We need to free the
   * m_cpolicy if it is allocated by this object. */
  bool m_allocated;
};

#endif
